### ISSUE TITLE
bump zlib to v1.2.12 in installation scripts

### ISSUE THREAD

**Issue by tricaric** [LLNL/spheral#127]
Hi, I am trying to install spheral, but the installation stops after failing to download zlib.
The current scripts attempt to download http://www.zlib.net/zlib-1.2.11.tar.gz
but apparently that is no longer available, has been replaced by http://www.zlib.net/zlib-1.2.12.tar.gz
If possible please update the installation scripts. Thanks.

**Comment by mdavis36** [comment]
How are you building? We recently moved to managing our TPLs with [Spack](https://github.com/spack/spack). The CMake TPL system is now deprecated. I was able to download and install zlib 1.2.11 through our spack process fine. Details on building and installing Spheral can be found [here](https://spheral.readthedocs.io/en/latest/building.html).

**Comment by tricaric** [comment]
Hi Michael, Thanks for your reply. I was trying to install it on a linux mint 20.3 system, initially using spack but somehow that was not working, then I tried to use cmake approach directly and that is when I encountered the zlib issue.

Now I have just installed a fresh ubuntu 20.04 image on virtualbox and I'm trying there and I'm happy to report that it is compiling as I'm writing this. A few differences maybe worth noticing: (I'm using docs/quickstart.rst as reference)
- I left the "gcc@9.3.0" commands even if the ubuntu 20.04 gcc appears to be 9.4.0;
- the generated cmake file name is a bit different from the instructions, it is:
    linux-ubuntu20.04-sandybridge-gcc@9.3.0.cmake
and the build dir is 
    build_linux-ubuntu20.04-sandybridge-gcc@9.3.0.cmake/build
but perhaps this has to do with how I configured virtualbox.

I plan to move to a proper native installation as soon as I get to know a bit better this software. Speaking of, the online documentation that I've found online seems to cover mostly the installation, is there a primer on how to setup and run some example cases? 
Thanks,
Pasquale

**Comment by mdavis36** [comment]
Hi Pasquale, 

I'm glad to hear you're making some headway, Ubuntu seems to have updated it's version of gcc to 9.4.0, it was 9.3.0 at the time of writing the documentation. Your host-config file and build directory name are generated depending on your operating system, compute architecture and compiler configuration. This helps those of us compiling across multiple machines keep track of our builds / configs. Since the compiler has slightly changed you might want to check out this section of the documentation that details how to configure for different compilers / operating systems.
https://spheral.readthedocs.io/en/latest/building.html#id2
This should also help you build on your mint system. The spack TPL process and documentation is relatively new, so you're feedback here is really useful to help me understand what does and doesn't make sense for users. 

Thank you,
Mike

**Comment by mdavis36** [comment]
After offline discussion with @tricaric it seems one of the biggest issues here involved lack of clarity in documentation for external users. This issue will be resolved with PR #138.
